### ISSUE TITLE
Extend to include Secret/Salt 

### ISSUE THREAD

**Issue by benghui-agora** [AgoraIO-Community/agora-token-service#23]
Request to extend this token service to include simple Secret & Salt generation for channel encryption. 
See
https://docs.agora.io/en/Interactive%20Broadcast/channel_encryption_web_ng?platform=Web

**Comment by digitallysavvy** [comment]
Thanks for your request but this feature is out of scope for this project. 

The use of encryption keys and salts is something that is unique to each team using these security features. 

Similarly this token server is meant for education and testing purposes and not meant for production purposes because it grants tokens to anyone that makes the request.
