### ISSUE TITLE
Heroku Deploy - 404

### ISSUE THREAD

**Issue by atannerd** [AgoraIO-Community/agora-token-service#46]
Trying to test out the single click deploy and everything builds fine.

When I try to ping the URL given by heroku to my app, I get 404.

I am assuming there is something obvious I am missing.

Any advice is much appreciated.

**Comment by atannerd** [comment]
This 404 is showing on the root page of the app as well as the /ping endpoint mentioned in the documentation.

Perhaps the /ping endpoint is simply meant as an example of how the messages and responses are structured.

Once I started testing the getToken endpoint, I did get a response.

I will leave this ticket open for now and let you decide if you want to use it to make the docs a little more clear and/or put a success message on the root page of the app for us "one clickers" to have an easy way to verify the app is up and running.

The getToken functionality seems to be working very well and I appreciate you making this code available.

**Comment by digitallysavvy** [comment]
Looking at the [service.go ](https://github.com/AgoraIO-Community/agora-token-service/blob/a04f110bd5aa9e2dead77ffa20e107328da00f9b/service/service.go) it looks like the `/ping` endpoint was removed. 

It's not really needed so the best idea would be to remove it from the README, because the `getToken` endpoint serves the purpose of checking if the service works without  the need for any superfluous endpoints.

**Comment by maxxfrazer** [comment]
`/ping` endpoint re-added. apologies about that!
