### ISSUE TITLE
Questions about token service

### ISSUE THREAD

**Issue by koufopoulosf** [AgoraIO-Community/agora-token-service#57]
Hello 👋

I just wanted to ask two questions about the agora token service:

1. Since audio/video call features of flutter apps require notifications, and many devs are using FCM (Firebase Cloud Messaging) for this option, wouldn't it make more sense to use a firebase cloud function for generating the tokens? Instead of this golang service (which I personally like) ?

2. If this golang service is mandatory (and firebase cloud functions are discouraged), which service would be better to deploy for production? Heroku? Railway? Render? And which plan would be the ideal one?

Thanks in advance!

**Comment by digitallysavvy** [comment]
@koufopoulosf 

This token server is just an example implementation that is meant to help developers implement Agora's SDK's quicker into their apps whether they are web, iOS, Android, Flutter, Unity, or Unreal. The quick deploy options are meant to make it easier for front end developers to keep moving in their development without having to spend the time themselves or wait for a backend engineer to set up a token server.

That being said, you don't have to use this token server, you can implement the token generation using firebase cloud functions and express if you would prefer. We don't recommend this over other solutions because this token server on its own isn't meant for production purposes as it doesn't have any security built into it to ensure authorized users are requesting tokens.

Here's an example of a token server using express: [ExpressJs Token Server Example](https://github.com/AgoraIO-Community/Agora-Node-TokenServer) or you can use whichever language you prefer [see the full list in AgoraIO/Tools](https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey)

**Comment by koufopoulosf** [comment]
@digitallysavvy Thanks for the detailed reply, I highly appreciate it!
