### ISSUE TITLE
No https configure in window

### ISSUE THREAD

**Issue by royaldragonit** [AgoraIO-Community/agora-token-service#62]
Only http://0.0.0.0:8080 running on window. Not working on https

**Comment by digitallysavvy** [comment]
@royaldragonit thanks for your interest in this Token Service project.

The http/https issue you are facing is in because of the repo, this is how locally hosted web servers run. When working on localhost you don't have an https, only http. To use an https connection locally, you need to create your own certificate to use for signing. There are a number of guides online that can walk you through this. 

Reference guides: 
- [Use HTTPS for local development ](https://web.dev/articles/how-to-use-local-https)
- [How to Run HTTPS on Localhost: A Step-by-Step Guide](https://akshitb.medium.com/how-to-run-https-on-localhost-a-step-by-step-guide-c61fde893771)
